password = Password
open = Open
save = Save
copy = Copy
paste = Paste
cut = Cut
search = Search
close = Close
enter_text = Enter text
status = Status 
show_passwod = Show password
hide_password = Hide password
! about = About
about_us = About Us
exit = Exit
file = File
edit = Edit
settings = Settings
help = Help
languages = Languages
select_a_language = Select a Language
