name: release_linux

on:
  push:
    branches: ["main"]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
         sudo apt-get update -y          
         curl https://sh.rustup.rs -sSf | sh -s -- -y
         source $HOME/.cargo/env
         cargo --version
         
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: compile linux
        run: |
          source $HOME/.cargo/env          
          cargo build --release 
 
          
      - name: rename binaries 
        run: |
          cp target/release/ct target/release/ct_linux

      - name: Upload Linux Binary to release
        if: github.repository_owner == 'myridia'                  
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'target/release/ct_linux'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true



          


    
   


        


        


 
     
