name: macos_release
on:
  push:
    branches: ["main"]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  build_macos:
    runs-on: macos-15
    steps:
      - name: install Rust
        run: |
          brew install llvm tree 
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          rustup target add x86_64-apple-darwin
          rustup component add llvm-tools-preview
          cargo --version 
          
      - name: checkout repo
        uses: actions/checkout@v4
 

      - name: compile macos
        run: |
          cargo build --release  --target x86_64-apple-darwin 
          cargo build --release  
      - name: list macos binary
        run: |
          cd target
          tree . 
      - name: rename macos binary
        run: |
          cp target/release/ct release/ct_macos
          cp target/x86_64-apple-darwin/release/ct ct_macos_intel.app


      - name: Upload Macos Intel Binary to release
        if: github.repository_owner == 'myridia'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'ct_macos_intel.app'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true   

      - name: Upload Macos Silicaon Binary to release
        if: github.repository_owner == 'myridia'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'ct_macos.app'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true 

    
          
