name: macos_release
on:
  push:
    branches: ["main"]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  build_macos:
    runs-on: macos-15
    steps:
      - name: get_repository
        run: |
          #brew install rust rustc-completion
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          cargo --version 
          
      #- name: checkout repo
      #  uses: actions/checkout@v4
 

      #- name: compile macos
      #  run: |
      #    cargo build --release 

      #- name: list macos binary
      #  run: |
      #    ls target/release
          
      #- name: rename macos binary
      #  run: |
      #    cp target/release/ct target/release/ct_macos

      #- name: Upload Macos Intel Binary to release
      #  if: github.repository_owner == 'myridia'
      #  uses: svenstaro/upload-release-action@v2
      #  with:
      #    repo_token: ${{ secrets.GITHUB_TOKEN }}
      #    file: 'target/release/ct_macos'
      #    tag: ${{ github.ref }}
      #    overwrite: true
      #    file_glob: true   

    
          
