name: Windows
on:
  push:
    branches: ["main"]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none
  
jobs:
  build-msix:
    runs-on: windows-latest # Use a Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MSIX Packaging Tool
        run: |
           winget install --id Microsoft.MSIXPackagingTool -e --accept-source-agreements --accept-package-agreements --silent


      - name: Set up MSBuild (if your app uses it)
        uses: microsoft/MSBuild-Tool@v1 # Use an MSBuild setup action if needed for your build

      - name: Build Application (Example - Adjust for your build process)
        run: |
          dir 
       

 
