name: Windows
on:
  push:
    branches: ["main"]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none
  
jobs:
  build-msix:
    runs-on: windows-latest # Use a Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependencies
        run: |
           winget install --id Microsoft.MSIXPackagingTool -e --accept-source-agreements --accept-package-agreements --silent

      - name: Download_exe 
        run: |
         curl -L "https://github.com/myridia/ct/releases/download/main/ct.exe" -o "./ct.exe"
         
          
      #- name: SKD
      #  uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.6 
        
      - name: Certificate 
        run: |
          # $folder = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64\"
          # $currentPath = $env:Path
          # $env:Path = "$folder;$currentPath"
          $pass = ConvertTo-SecureString "passpass" -AsPlainText -Force
          $loc = "Cert:\CurrentUser\My"
          # $cert = New-SelfSignedCertificate -Subject "CN=Myridia" -CertStoreLocation $loc -KeyExportPolicy Exportable -KeyUsage DigitalSignature -FriendlyName "Myridia Certificate"
            $cert = New-SelfSignedCertificate -Subject "CN=Myridia" -CertStoreLocation $loc -KeyExportPolicy Exportable -KeyUsage CertSign,CrlSign -FriendlyName "Myridia Root CA"
          if ($cert) {
            $certp = "Cert:\CurrentUser\My\$($cert.Thumbprint)"
            Export-PfxCertificate  -cert $certp  -FilePath ".\Myridia.pfx" -Password $pass -Force
            Export-Certificate -Cert "Cert:\CurrentUser\My\$($cert.Thumbprint)" -FilePath ".\Myridia.cer" -Force 
            certutil -addstore Root ".\Myridia.cer"

          } else {
            Write-Error "Certificate generation failed."
          }

          $caCert = Get-ChildItem -Path $loc | Where-Object { $_.Subject -eq "CN=Myridia" }
          $cert = New-SelfSignedCertificate  -Signer $caCert -Subject "CN=Ct" -CertStoreLocation $loc -KeyExportPolicy Exportable -KeyUsage DigitalSignature -FriendlyName "CT Certificate" -Type CodeSigningCert
          if ($cert) {
            $certp = "Cert:\CurrentUser\My\$($cert.Thumbprint)"
            Export-PfxCertificate  -cert $certp  -FilePath ".\Ct.pfx" -Password $pass -Force
            Export-Certificate -Cert "Cert:\CurrentUser\My\$($cert.Thumbprint)" -FilePath ".\Ct.cer" -Force 
          } else {
            Write-Error "Certificate generation failed."  
          }

      - name: Sign  
        run: |
          dir
          # Import-Certificate -FilePath ".\Ct.cer" -CertStoreLocation Cert:\CurrentUser\Root -Confirm:$false 
          $cert = Get-PfxCertificate -FilePath ".\Ct.pfx" -Password $pass
          Set-AuthenticodeSignature -FilePath ".\ct.exe" -Certificate $cert
          # Import-Certificate -FilePath ".\Ct.cer" -CertStoreLocation Cert:\CurrentUser\Root
          # Import-Certificate -FilePath "cert:\CurrentUser\My\$($cert.Thumbprint)" -CertStoreLocation Cert:\CurrentUser\Root
          # Set-AuthenticodeSignature -FilePath ".\ct.exe" -Certificate $cert
          # $pfx = Get-PfxCertificate -FilePath ".\Ct.pfx" -Password $pass
          # $pfx.HasPrivateKey
          # passpass" /v /f Ct.pfx /t http://timestamp.digicert.com /fd sha256 ct.exe
          # signtool sign /v /f Ct.pfx /p passpass /fd sha256 ct.exe
          # signtool verify /pa "ct.exe"
          # where signtool
          


       

 
