name: Windows
on:
  push:
    branches: ["main"]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Install Rust          
        uses: actions-rs/toolchain@v1 
        with:
          toolchain: nightly 

      - name: Build
        run: |
          cargo build --release
           
      - name: Release
        if: github.repository_owner == 'myridia'                  
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'target/release/ct.exe'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true


          

          


    
   


        


        


 
     
